#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/rustdesk/rustdesk /usr/bin/rustdesk

	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/nomad.service ]; then
			rm /etc/systemd/system/nomad.service /usr/lib/systemd/system/nomad.service >/dev/null 2>&1
		fi
		# Also clean up legacy rustdesk.service if present
		if [ -e /usr/lib/systemd/system/rustdesk.service ]; then
			systemctl stop rustdesk >/dev/null 2>&1 || true
			systemctl disable rustdesk >/dev/null 2>&1 || true
			rm -f /usr/lib/systemd/system/rustdesk.service
		fi
        mkdir -p /usr/lib/systemd/system/
		cp /usr/share/rustdesk/files/systemd/nomad.service /usr/lib/systemd/system/nomad.service
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/nomad.service
		fi
		systemctl daemon-reload
		systemctl enable nomad
		systemctl start nomad
	fi
fi
